# **Handwritten Equation Solver**

**Importing necessary dependencies** 

In [1]:
import os
import cv2
import numpy as np
import pandas as pd
from numpy.random import seed
from tensorflow.random import set_seed
from PIL import Image
from os import listdir
from os.path import isfile, join
from matplotlib import pyplot as plt

**Defining function to read images and performing various operations**

In [2]:
seed(5)
set_seed(7)

def load_img_from_folder(folder):
    train_data = []
    for filename in np.random.choice(os.listdir(folder), 4000):
        img = cv2.imread(os.path.join(folder, filename), cv2.IMREAD_GRAYSCALE)
        img=~img
        #only one time
        #cv2.imshow("frame", img)
        if img is not None:
            _, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
            ctrs,_ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
            max_ = 0
            for c in ctrs:
                x, y, w, h = cv2.boundingRect(c)
                max_ = max(w*h, max_)
                if max_ == w*h:
                    x_max = x
                    y_max = y
                    w_max = w
                    h_max = h
                    
            im_crop = thresh[y_max:(y_max+h_max+10), x_max:(x_max+w_max+10)]
            im_resize = cv2.resize(im_crop, (28, 28))
            im_resize = np.reshape(im_resize, (784, 1))
            train_data.append(im_resize)
    return train_data

**Creating the Training Set**

In [3]:
data = []

In [4]:
#assign "-" = 10
data = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\-")
for i in range(len(data)):
    data[i] = np.append(data[i], [10])
print(len(data))

4000


In [5]:
#assign "+" = 11
data1 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\+")
for i in range(len(data1)):
    data1[i] = np.append(data1[i], [11])

data = np.concatenate((data, data1))
print(len(data))

8000


In [6]:
data2 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\0")
for i in range(len(data2)):
    data2[i] = np.append(data2[i], [0])

data = np.concatenate((data, data2))
print(len(data))

12000


In [7]:
data3 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\1")
for i in range(len(data3)):
    data3[i] = np.append(data3[i], [1])

data = np.concatenate((data, data3))
print(len(data))

16000


In [8]:
data4 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\2")
for i in range(len(data4)):
    data4[i] = np.append(data4[i], [2])

data = np.concatenate((data, data4))
print(len(data))

20000


In [9]:
data5 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\3")
for i in range(len(data5)):
    data5[i] = np.append(data5[i], [3])

data = np.concatenate((data, data5))
print(len(data))

24000


In [10]:
data6 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\4")
for i in range(len(data6)):
    data6[i] = np.append(data6[i], [4])

data = np.concatenate((data, data6))
print(len(data))

28000


In [11]:
data7 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\5")
for i in range(len(data7)):
    data7[i] = np.append(data7[i], [5])

data = np.concatenate((data, data7))
print(len(data))

32000


In [12]:
data8 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\6")
for i in range(len(data8)):
    data8[i] = np.append(data8[i], [6])

data = np.concatenate((data, data8))
print(len(data))

36000


In [13]:
data9 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\7")
for i in range(len(data9)):
    data9[i] = np.append(data9[i], [7])

data = np.concatenate((data, data9))
print(len(data))

40000


In [14]:
data10 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\8")
for i in range(len(data10)):
    data10[i] = np.append(data10[i], [8])

data = np.concatenate((data, data10))
print(len(data))

44000


In [15]:
data11 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\9")
for i in range(len(data11)):
    data11[i] = np.append(data11[i], [9])

data = np.concatenate((data, data11))
print(len(data))

48000


In [16]:
data12 = load_img_from_folder("C:\\Users\\DELL\\Downloads\\archive (2)\\extracted_images\\Symbol\\x")
for i in range(len(data12)):
    data12[i] = np.append(data12[i], [12])

data = np.concatenate((data, data12))
print(len(data))

52000


In [17]:
data.shape

(52000, 785)

**Final Training Set**

In [18]:
df_train = pd.DataFrame(data, index = None)

In [19]:
df_train.shape

(52000, 785)

In [20]:
df_train.head()

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  778  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
2  255  255    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3  255  255  255  255  255  255   14    0    0    0  ...    0    0    0    0   
4  255  255  255  255  255  255  255    0    0    0  ...    0    0    0    0   

   779  780  781  782  783  784  
0    0    0    0    0    0   10  
1    0    0    0    0    0   10  
2    0    0    0    0    0   10  
3    0    0    0    0    0   10  
4    0    0    0    0    0   10  

[5 rows x 785 columns]

**Converting Labels to Categorical data**

In [21]:
labels = df_train.iloc[:, -1].values

**Separating labels column from training set** 

In [22]:
df_train.drop(df_train.columns[[784]],axis=1,inplace=True)

In [23]:
df_train.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
2  255  255    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3  255  255  255  255  255  255   14    0    0    0  ...    0    0    0    0   
4  255  255  255  255  255  255  255    0    0    0  ...    0    0    0    0   

   778  779  780  781  782  783  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 784 columns]

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df_train, labels, test_size = 0.2, random_state = 0)

In [25]:
print(y_train)

[ 1  1  8 ...  8  8 10]


In [26]:
from keras.utils.np_utils import to_categorical
cat = to_categorical(y_train, num_classes = 13)

In [27]:
print(cat[0])

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Importing necessary dependencies** 

In [28]:
np.random.seed(1212)
import keras
from keras.layers import *
from keras import optimizers
from keras.models import Model
from keras.layers import Dense
from keras import backend as K
from keras.layers import Dropout
from keras.layers import Flatten
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Input
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D

**Transforming Training Set**

In [29]:
l = []
for i in range(len(x_train)):
    l.append(np.array(x_train[i:i+1]).reshape(28, 28, 1))

**Creating the CNN Model**

In [30]:
model = Sequential()
model.add(Conv2D(30, (5, 5), input_shape = (28, 28, 1), activation= "relu"))
model.add(MaxPooling2D(pool_size = (2, 2)))
model.add(Conv2D(15, (3,3), activation = "relu"))
model.add(MaxPooling2D(pool_size = (2, 2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(128, activation = "relu"))
model.add(Dense(50, activation = "relu"))
model.add(Dense(13, activation = "softmax"))

model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

**Training the Model**

In [31]:
model.fit(np.array(l), cat, validation_split=0.2, epochs=50, batch_size=200)

Epoch 1/50
167/167 [==============================] - 25s 66ms/step - loss: 0.4716 - accuracy: 0.3696 - val_loss: 0.0573 - val_accuracy: 0.8903
Epoch 2/50
167/167 [==============================] - 11s 63ms/step - loss: 0.0623 - accuracy: 0.8787 - val_loss: 0.0325 - val_accuracy: 0.9440
Epoch 3/50
167/167 [==============================] - 11s 63ms/step - loss: 0.0410 - accuracy: 0.9267 - val_loss: 0.0228 - val_accuracy: 0.9596
Epoch 4/50
167/167 [==============================] - 11s 66ms/step - loss: 0.0310 - accuracy: 0.9434 - val_loss: 0.0181 - val_accuracy: 0.9695
Epoch 5/50
167/167 [==============================] - 11s 66ms/step - loss: 0.0237 - accuracy: 0.9583 - val_loss: 0.0153 - val_accuracy: 0.9751
Epoch 6/50
167/167 [==============================] - 11s 65ms/step - loss: 0.0199 - accuracy: 0.9680 - val_loss: 0.0117 - val_accuracy: 0.9828
Epoch 7/50
167/167 [==============================] - 12s 70ms/step - loss: 0.0175 - accuracy: 0.9714 - val_loss: 0.0108 - val_accuracy:

In [32]:
l1 = []
for i in range(len(x_test)):
    l1.append(np.array(x_test[i:i+1]).reshape(28, 28, 1))

In [33]:
result = model.predict_classes(np.array(l1))

C:\Users\DELL\anaconda3\lib\site-packages\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [34]:
print(result)

[8 7 6 ... 6 8 7]


In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, result)
print(cm)
accuracy_score(y_test, result)

[[801   0   0   0   1   0   0   0   0   0   0   0   0]
 [  1 767   5   0   3   0   0   4   0   1   0   0   1]
 [  1   1 801   1   0   2   0   5   0   0   0   0   0]
 [  0   1   0 825   2   5   0   2   1   1   0   0   0]
 [  0   1   0   0 796   0   0   0   0   2   1   0   0]
 [  0   0   0   0   0 767   1   0   1   0   0   0   0]
 [  0   0   0   0   1   0 828   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 781   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 803   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0 770   0   0   0]
 [  0   3   0   0   0   2   0   0   0   0 766   0   0]
 [  0   1   0   0   4   0   0   3   0   0   1 787   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0 848]]


0.9942307692307693

**Testing the Model**

In [36]:
img = cv2.imread(r"C:\Users\DELL\test images\t1.jfif", cv2.IMREAD_GRAYSCALE)
cv2.imshow("wo", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

if img is not None:
    img =~img
    _, thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
    
    cv2.imshow("work", thresh)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
    ctrs, _ = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    cnt=sorted(ctrs, key=lambda ctr: cv2.boundingRect(ctr)[0])
    train_data = []
    rects = []
    
    max_area = 0
    area = []
    for c in cnt:
        x, y, w, h = cv2.boundingRect(c)
        area.append(w*h)
        max_area = max(max_area, w*h)
    
    for c in cnt:
        x, y, w, h = cv2.boundingRect(c)
        rect = [x, y, w, h]
        if w*h > max_area/40:
            rects.append(rect)
    
    bool_rect = []
    for r in rects:
        l = []
        for rec in rects:
            flag = 0
            if rec!= r:
                if r[0]<(rec[0]+rec[2]+10) and rec[0]<(r[0]+r[2]+10) and r[1]<(rec[1]+rec[3]+10) and rec[1]<(r[1]+r[3]+10):
                    flag = 1
                l.append(flag)
            if rec == r:
                l.append(0)
        bool_rect.append(l)
        
    dump_rect=[]
    for i in range(0,len(rects)):
        for j in range(0,len(rects)):
            if bool_rect[i][j]==1:
                area1=rects[i][2]*rects[i][3]
                area2=rects[j][2]*rects[j][3]
                if(area1==min(area1,area2)):
                    dump_rect.append(rects[i])
        
    final_rect = [i for i in rects if i not in dump_rect]
    
    for r in final_rect:
        x = r[0]
        y = r[1]
        w = r[2]
        h = r[3]
        im_crop = thresh[y:(y+h+10), x:(x+w+10)]

        cv2.imshow("work", im_crop)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
        
        im_resize = cv2.resize(im_crop, (28, 28))
        cv2.imshow("work", im_resize)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

        im_resize=np.reshape(im_resize,(28,28,1))
        train_data.append(im_resize)
         

**Printing the Equation written on test image**

In [37]:
s=''
for i in range(len(train_data)):
    train_data[i]=np.array(train_data[i])
    train_data[i]=np.reshape(train_data[i], (28,28,1))
    train_data[i] = np.expand_dims(train_data[i], axis = 0)
    result = model.predict_classes(train_data[i])
    
    if(result[0]==10):
        s=s+'-'
    if(result[0]==11):
        s=s+'+'
    if(result[0]==12):
        s=s+'*'
    if(result[0]==0):
        s=s+'0'
    if(result[0]==1):
        s=s+'1'
    if(result[0]==2):
        s=s+'2'
    if(result[0]==3):
        s=s+'3'
    if(result[0]==4):
        s=s+'4'
    if(result[0]==5):
        s=s+'5'
    if(result[0]==6):
        s=s+'6'
    if(result[0]==7):
        s=s+'7'
    if(result[0]==8):
        s=s+'8'
    if(result[0]==9):
        s=s+'9'
    
print(s)


C:\Users\DELL\anaconda3\lib\site-packages\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


87+95


**Evaluating the Equation**

In [38]:
eval(s)

182